global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8001']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8001']

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8001']

  - job_name: 'cart-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cart-service:8001']